kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: stackelberg-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        scheduler:
          extraArgs:
            v: "2"
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
networking:
  disableDefaultCNI: false
  kubeProxyMode: "iptables"
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"